"""
========================================
BRIDGET AGENT GENERATION ENGINE
========================================

This module implements the human and AI agent's predictive pipelines.
It is structured as follows:

* User Base class: Models realistic human behaviour towards the AI, originally defined in the FRANK algorithm
[original code at: https://github.com/FedericoMz/Frank/tree/main]

* BetaUser subclass: Simulates user prediction mechanism modeled with the Instance-Dependent Label Noise (IDN) approach.
The mathematical formulation relies on the OpenL2D Synthetic Expert Generation Scheme 
(Alves, J. et al. (2025) A benchmarking framework and dataset for learning to defer in human-ai decision-making.
Source code available at: https://github.com/feedzai/openl2d/tree/main)

The formulation is revised hereby to adapt to the streaming learning context of BRIDGET's Human in Command phase.
Full reasoning and formal mathematical definition provided in:
https://drive.google.com/file/d/1J7ULywuyRuRCYHXtx1pa01Q_uasaheio/view?usp=sharing 

* DeferralNet: A 2-layer neural network classifier implemented in PyTorch, acting as the principal classifier
during the Machine in Command phase

* PyTorchWrapper: A custom wrapper compliant with sklearn's BaseEstimator for smooth deployment within the 
GrowingSpheres algorithm. Its definition is model agnostic.

"""


from bridget_utils import *
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.base import BaseEstimator
import torch
import numpy as np
import torch.nn as nn
import random


class User:

    """
    Args:
        belief_level (float): probability that the user trusts and accepts the prediction generated by the machine
        rethink_level (float): probability that the user changes their prior prediction when faced with inconsistency w.r.t.
        past decisions or when challenged by the machine
        fairness (float): parameter regulating the fairness of the user concerning the protected attributes
    """
    def __init__(self, belief_level, rethink_level, fairness):

        self.belief_level= belief_level
        self.rethink_level= rethink_level
        self.fairness= fairness

    
    def believe(self, seed=None):
        rng= random.Random(seed) if seed is not None else random
        
        if self.belief_level > 1:
            return None

        else:
            return rng.choices(population=[True, False], 
                            weights=[self.belief_level, 1-self.belief_level], k=1)[0]
    

    def rethink(self):
        return random.choices(population=[True, False], 
                            weights=[self.rethink_level, 1-self.rethink_level], k=1)[0]
    
    def fairness_percentage(self):
        return self.fairness
        


class BetaUser(User):
    
    """
    Simulation of the human expert parametrized in the respective expert_{dataset_name}.yaml file, according to the OpenL2D original scheme 
    Adapted to the streaming learning setting.

    Args:
        belief_level(float): Inherited by User class
        rethink_level(float): Inherited by User class
        fairness (float): Inherited by User class
        fpr (float): User's inherent False Positive Rate (defined in expert_{dataset_name}.yaml)
        fnr (float): User's inherent False Negative Rate (defined in expert_{dataset_name}.yaml)
        alpha (float): Representing the intra-rater agreement of the human expert (defined in expert_{dataset_name}.yaml)
        features_dict (dict): Distribution parameters (mean, std) relative to the feature matrix X. Indicate the influence of the single feature in the expert's prediction logic (defined in expert_{dataset_name}.yaml)
        seed (int): Ensuring reproducibility in the expert's prediction 
        
    Methods:
        __init__: Initializes user profiles and the weights dictionary
        sample_weights: Samples the feature weights from the distributions parametrized in expert_{dataset_name}.yaml
        search_bounds: Establishes search bound for the subsequent intercepts optimization process
        fit: Calibrates intercepts via a binary search bisection method to match the global FPR and FNR target established for each expert archetype.
        calc_probs_fp: Computes instance-dependent false positive error probabilities using the sigmoid.
        calc_probs_fn: Computes instance-dependent false negative error probabilities using the sigmoid.
        predict: Produces the expert's prediction for a certain instance, according to the label inversion scheme from OpenL2D
    """


    def __init__(self, 
                 belief_level, rethink_level, fairness, 
                 fpr, fnr,
                 alpha,  
                 features_dict,
                 seed
    ):
        
        super().__init__(belief_level, rethink_level, fairness)

        self.fpr= fpr
        self.fnr= fnr
        self.alpha= alpha
        self.features_dict= features_dict
        self.seed = seed
    
        self.fnr_beta= None
        self.fpr_beta= None
        self.w= None

    def sample_weights(self, X):

        if self.features_dict is None:
            raise ValueError("Features_dict not yet defined")
        
        else:
            np.random.seed(self.seed)
            self.feature_names = X.columns.tolist()
            self.w = np.zeros(X.shape[1])
            for feature in self.features_dict.keys():
                self.w[X.columns.get_loc(feature)] = np.random.normal(
                    loc = self.features_dict[feature][0], scale = self.features_dict[feature][1]
                    )


    
    def search_bounds( self, X, y, error, beta_target):
        
        lower_b, upper_b = -200, 200
       
        for i in range(5):

            #1. False Positive
            if error == 'fp':
                self.fpr_beta = lower_b
                self.calc_probs_fp(X, y)
                mean_lower = float(self.error_prob.loc[y == 0, 'p_of_fp'].mean())

                self.fpr_beta = upper_b
                self.calc_probs_fp(X,y)
                mean_upper = float(self.error_prob.loc[y == 0, 'p_of_fp'].mean()) 


            #2. False Negative 
            elif error == 'fn': 
                self.fnr_beta= lower_b
                self.calc_probs_fn(X, y)
                mean_lower = float(self.error_prob.loc[y == 1, 'p_of_fn'].mean())

                self.fnr_beta= upper_b
                self.calc_probs_fn(X,y)
                mean_upper = float(self.error_prob.loc[y == 1, 'p_of_fn'].mean()) 


            if (mean_lower - beta_target) * (mean_upper - beta_target) < 0:
                return lower_b, upper_b, mean_lower, mean_upper

            lower_b -= 200
            upper_b += 200
 

    def fit(self, X, y, tol):
        self.sample_weights(X)

        self.error_prob= pd.DataFrame(np.nan, index=X.index, columns=['p_of_fp', 'p_of_fn'])
        

        # fitting for FPR
        fpr_l, fpr_u, fp_mean_lower, fp_mean_upper = self.search_bounds(X, y, 'fp', self.fpr)

        self.fpr_beta= (fpr_l + fpr_u) / 2 
        self.calc_probs_fp(X,y)
        fp_mean= self.error_prob.loc[y == 0, 'p_of_fp'].mean() 

        fpr_iters= 0
        while np.abs(fp_mean - self.fpr) > tol:
            if (fp_mean_lower - self.fpr) * (fp_mean - self.fpr) < 0:
                fpr_u =self.fpr_beta
                fp_mean_upper= fp_mean
            else:
                fpr_l= self.fpr_beta
                fp_mean_lower= fp_mean
            
            self.fpr_beta= (fpr_u + fpr_l)/2
            self.calc_probs_fp(X,y)
            fp_mean= self.error_prob.loc[y == 0, 'p_of_fp'].mean() 
            fpr_iters += 1 ## conteggio solo da mettere nel dict finale



        # fitting for FNR
        fnr_l, fnr_u, fn_mean_lower, fn_mean_upper = self.search_bounds(X, y, 'fn', self.fnr)

        self.fnr_beta= (fnr_l + fnr_u) / 2 
        self.calc_probs_fn(X,y)
        fn_mean= self.error_prob.loc[y == 1, 'p_of_fn'].mean() 


        fnr_iters= 0
        while np.abs(fn_mean - self.fnr) > tol:
            if (fn_mean_lower - self.fnr) * (fn_mean - self.fnr) < 0:
                fnr_u= self.fnr_beta
                fn_mean_upper= fn_mean
            else:
                fnr_l= self.fnr_beta
                fn_mean_lower= fn_mean

            self.fnr_beta= (fnr_u + fnr_l)/2
            self.calc_probs_fn(X,y)
            fn_mean= self.error_prob.loc[y == 1, 'p_of_fn'].mean() 
            fnr_iters+= 1
        

        # compiling results
        fit_res = {
            "fpr iters number": fpr_iters,
            "calibrated_fpr_beta": self.fpr_beta,
            "target_fpr": self.fpr,
            "achieved_fpr": fp_mean,

            "fnr iters number": fnr_iters,
            "calibrated_fnr_beta": self.fnr_beta,
            "target_fnr": self.fnr,
            "achieved_fnr": fn_mean,

            "feature_weights": dict(zip(X.columns, self.w)),
        }

        return fit_res
   
    
    def calc_probs_fp(self, X, y): 
        if self.w is None:
            raise ValueError('Synthetic expert must be .fit() to the data.')
        
        weights = self.w
        dot_prod= X.dot(weights)
        weights_norm= np.linalg.norm(weights)

        term = dot_prod/weights_norm
        
        z_dec = self.fpr_beta + (self.alpha * term)
        probability_of_fp = sigmoid(z_dec)

        mask = (y == 0)
    
        self.error_prob.loc[mask, 'p_of_fp'] = probability_of_fp[mask]

    def calc_probs_fn(self, X, y):  
        if self.w is None:
            raise ValueError('Synthetic expert must be .fit() to the data.')
       
        weights = self.w
        weights_norm= np.linalg.norm(weights)

        dot_prod = X.dot(weights)
        term = dot_prod / weights_norm
     
        z_dec= self.fnr_beta - (self.alpha*term)
        probability_of_fn= z_dec.apply(sigmoid)

        mask = (y==1)

        self.error_prob.loc[mask, 'p_of_fn'] = probability_of_fn[mask]


    def predict(self, record, ground, iter):  
    
        """
        Whereas OpenL2D supports batch-wise prediction, this function is designed to work for a streaming learning context
        For this reason single records are evaluated one at a time.

        Args:
            record (dict, Tensor or array-like): Input feature attributes representing the current row
            ground (int): The true ground truth label of the target record instance
            iter (int): Index used to assign the seed for ensuring reproducibility

        Returns:

            int: The simulated user's classification prediction (0 or 1)
        """

        if self.w is None:
            raise ValueError('Synthetic expert must be .fit() to the data.')
        
        if isinstance(record, dict):
            record_arr = np.array([record[f] for f in self.feature_names])

        else:
            if torch.is_tensor(record):
                record_arr = record.detach().cpu().numpy()
            else:
                record_arr = np.array(record)

        if record_arr.shape[0] != self.w.shape[0]:
            print(f"Theres a mismatch, feature dict has shape {self.w.shape[0]}, record has {record.shape[0]}")

        
        weights = self.w
        weights_norm= np.linalg.norm(weights) 

        ground_arr= np.array([ground]) # necessary to call the invert_labels_with_probabilities function

        norm_feature_term= np.dot(record_arr, weights)/weights_norm

        if ground == 0:
            fpr_argument= self.fpr_beta + (self.alpha*(norm_feature_term))
            probability_of_fp= sigmoid(fpr_argument)
            probability_of_fn= 0
        
        else:
            fnr_argument= self.fnr_beta - (self.alpha*(norm_feature_term))
            probability_of_fn= sigmoid(fnr_argument)
            probability_of_fp= 0
        
        
        probability_of_error = probability_of_fn + probability_of_fp

        decisions = invert_labels_with_probabilities(
            labels_arr=ground_arr,
            p_arr=probability_of_error,
            seed=self.seed+iter
        )

        return int(decisions[0]) # this is the case of a binary 0/1 decision, must be adapted otherwise



class DeferralNet(nn.Module):

    """
    DNN structure implemented with PyTorch.
    Currently comprised of 2 hidden layers, ReLU activation. Loss function is defined in orchestrator.py (CE Loss was used in BRIDGET's experimental validation)
    
    Args:
        input_size (int): Dimension of the input feature matrix
        hidden_layer1 (int): First hidden layer neurons count (architecture defined in master_config.py, NET_CONFIGS)
        hidden_layer2 (int): Second hidden layer neurons count (architecture defined in master_config.py, NET_CONFIGS)
        output_size (int): Number of target classes (architecture defined in master_config.py, NET_CONFIGS)
        ::note: The Two-Stage Deferral Strategy requires 1 output neuron, representing the computed probability of
        deferring the input instance. In this context its retrieve in master_config.py, R_NET_CONFIGS
        dropout_coeff (float, optional): Neuron dropout coefficient for regularization purposes

        x (Tensor or array-like): Feature matrix for the input instance
        device (torch.device, optional): Either CPU or CUDA

    """
    def __init__(self, input_size, hidden_layer1, hidden_layer2, output_size, dropout_coeff=None):
        super(DeferralNet, self).__init__()

        self.softmax = nn.Softmax(dim=1)

        self.linear_relu_stack = nn.Sequential(
            nn.Linear(input_size, hidden_layer1),
            nn.ReLU(),
            nn.Dropout(dropout_coeff),

            nn.Linear(hidden_layer1, hidden_layer2),
            nn.ReLU(),
            nn.Dropout(dropout_coeff),
            nn.Linear(hidden_layer2, output_size)
        )
        
    def forward(self, x):
        logits = self.linear_relu_stack(x)
        return logits
    

    def predict_proba_nn(self, x, device= None):
        self.eval()

        with torch.no_grad():
            if not torch.is_tensor(x):
                x = torch.tensor(x, dtype=torch.float32).to(device)
            
            if x.ndim == 1:
                x = x.unsqueeze(0)
            x= x.to(device)
            logits = self.forward(x)
            return torch.softmax(logits, dim=1).cpu().numpy()

    def predict(self, x, device=None):
        probas= self.predict_proba_nn(x, device)
        return np.argmax(probas, axis=1)




class PyTorchWrapper(BaseEstimator):  
    
    """
    Model agnostic Wrapper for smooth interactions between the PyTorch model and the GrowingSpheres algorithm, compliant with sklearn's BaseEstimator 
    
    Args:
        model (object, DeferralNet): 
        target (str): Identifier of the target label
        features_names (list): List of attribute column names in str format
    
    """
    def __init__(self, model, target, features_names):
        self.model = model
        self.target= target
        self.features_names= features_names

    def predict(self, X):
        """
        Computes batch prediction

        Args: 
            X (dict, DataFrame or array-like): Input feature matrix

        Returns:
            ndarray: Numpy array containing predicted integer class label
        """
        self.model.eval() 
         
        if isinstance(X, dict):
            X = np.array([[X[f] for f in self.features_names]])

        if isinstance(X, pd.DataFrame):
            X= X[self.features_names].values
        
        X_t = torch.tensor(X, dtype= torch.float32)
        device = next(self.model.parameters()).device
    
        X_t = X_t.to(device)

        with torch.no_grad():
            outputs = self.model(X_t)
            preds = torch.argmax(outputs, dim=1).cpu().numpy()
        return preds


    def predict_proba(self, X):
        """
        Computes batch class probabilities using Softmax

        Args: 
            X (dict, DataFrame or array-like): Input feature matrix

        Returns:
            ndarray: Numpy array containing class probability distributions
        """
        self.model.eval() 
        
        if isinstance(X, dict):
            
            X = np.array([[X[f] for f in self.features_names]])

        if isinstance(X, pd.DataFrame):
             X= X[self.features_names].values
        
        X_t = torch.tensor(X, dtype= torch.float32)

        with torch.no_grad():
            outputs = self.model(X_t)
            probas= torch.softmax(outputs, dim= 1).numpy()

        return probas
    
    
    def predict_one(self, x):
        """
        Computes single instance prediction

        Args: 
            x (dict, DataFrame or array-like): Feature matrix for instance x

        Returns:
            int: Predicted classification label
        """


        self.model.eval() 

        if isinstance(x, dict):
            x_input = np.array([[x[f] for f in self.features_names]], dtype=np.float32)

        else:
            x_input = np.array(x, dtype=np.float32).reshape(-1, 8)  

        with torch.no_grad():
            res = self.model(torch.from_numpy(x_input))
        return int(torch.argmax(res, dim=1).item())




